// this module is temporary. It will be generated by backend.

export type CompileResponse =
  | { type: 'COMPILE_OK'; payload: { result: string } }
  | { type: 'COMPILE_ERR'; payload: { message: string } };

export type CompileRequest = { source: string };
