// this module is temporary. It will be generated by backend.

export type CompilationResult =
  | { type: 'SUCCESS'; payload: { result: string } }
  | { type: 'FAILURE'; payload: { message: string } };

export type CompilationRequest = { source: string };
