module.exports = {
  path: ['./ARCHITECTURE.md'],
  ignore: ['./crates/*', './packages/*'],
  transforms: {
    /* Match <!-- AUTO-GENERATED-CONTENT:START (LOLZ) --> */
    LOLZ(content, options) {
      return `This section was generated by the cli config markdown.config.js file`;
    },
  },
  callback: function () {
    console.log('markdown processing done');
  },
};
