ARG REGISTRY_PATH=docker.io/paritytech

# paritytech/base-ci-linux:latest
FROM ${REGISTRY_PATH}/base-ci-linux:ee3f4073-20230720
ARG RUST_NIGHTLY="2023-06-01"
ARG RUST_VERSION="1.69.0"

WORKDIR /builds

RUN set -eux; \
  rustup install ${RUST_VERSION} && \
  rustup default ${RUST_VERSION} && \
  rustup toolchain install ${RUST_VERSION} && \
  rustup target add wasm32-unknown-unknown --toolchain ${RUST_VERSION} && \
  	rustup component add rust-src --toolchain ${RUST_VERSION} && \
  	rustup component add rustfmt --toolchain ${RUST_VERSION}

RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

ARG CRAGO_CONTRACT_VERSION="2.1.0"

RUN cargo install --force --locked cargo-contract --version ${CRAGO_CONTRACT_VERSION}
ENV CARGO_TARGET_DIR="/target"
RUN cargo contract new contract

ARG INK_VERSION="4.0.1"

RUN cd contract && cargo update -p ink_e2e --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_storage --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_env --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_e2e_macro --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_macro --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_codegen --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_ir --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_engine --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_storage_traits --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_metadata --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_primitives --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_allocator --precise ${INK_VERSION}
RUN cd contract && cargo update -p ink_prelude --precise ${INK_VERSION}
RUN cd contract && cargo update -p contract-build --precise ${CRAGO_CONTRACT_VERSION}
RUN cd contract && cargo update -p colored --precise 2.0.4
RUN cd contract && cargo update -p clap --precise 4.1.8

RUN cd contract && cargo contract build
RUN cd contract && cargo test

WORKDIR /builds/contract