// Copyright 2018-2021 Parity Technologies (UK) Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub mod package_json;

use crate::{
    bindings::package_json::{
        generate_package_json,
        PackageJson,
    },
    services::compile,
};
use std::{
    io::Result,
    path::PathBuf,
};
use ts_rs::export;

export! {
   compile::CompilationResult,
   compile::CompilationRequest
   =>
   "../../node_modules/@paritytech/commontypes/src/index.d.ts"
}

#[test]
pub fn generate_package_json_to_node_modules() -> Result<()> {
    let project_dir_path = PathBuf::from("../../node_modules/@paritytech/commontypes");

    let package_json = PackageJson {
        name: "@paritytech/commontypes".to_string(),
        types: "src/index.d.ts".to_string(),
        description: "Type definitions generated by playground backend.".to_string(),
    };

    generate_package_json(&package_json, &project_dir_path)?;

    Ok(())
}
