name: Makefile

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - uses: actions/checkout@v3

      - name: Install
        run: make install

      - name: Install required rust toolchain
        run: rustup toolchain install nightly-2022-05-24

      - name: Add rust-src to toolchain
        run: rustup component add rust-src --toolchain nightly-2022-05-24-x86_64-unknown-linux-gnu

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Generate
        run: make generate

      - name: Build
        run: make build

      - name: Run Backend
        run: make backend-run
